// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file public/v1/public.proto (package public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file public/v1/public.proto.
 */
export const file_public_v1_public: GenFile = /*@__PURE__*/
  fileDesc("ChZwdWJsaWMvdjEvcHVibGljLnByb3RvEglwdWJsaWMudjEiLwoMTG9naW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIg8KDUxvZ2luUmVzcG9uc2UyRQoHU2VydmljZRI6CgVMb2dpbhIXLnB1YmxpYy52MS5Mb2dpblJlcXVlc3QaGC5wdWJsaWMudjEuTG9naW5SZXNwb25zZUIuWix3YXItb2YtZmFpdGgvcGtnL3Byb3RvYnVmL3B1YmxpYy92MTtwdWJsaWN2MWIGcHJvdG8z");

/**
 * Login
 *
 * @generated from message public.v1.LoginRequest
 */
export type LoginRequest = Message<"public.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message public.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_public_v1_public, 0);

/**
 * @generated from message public.v1.LoginResponse
 */
export type LoginResponse = Message<"public.v1.LoginResponse"> & {
};

/**
 * Describes the message public.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_public_v1_public, 1);

/**
 * @generated from service public.v1.Service
 */
export const Service: GenService<{
  /**
   * @generated from rpc public.v1.Service.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_public_v1_public, 0);

