// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file public/v1/public.proto (package public.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse } from "./public_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service public.v1.Service
 */
export const Service = {
  typeName: "public.v1.Service",
  methods: {
    /**
     * @generated from rpc public.v1.Service.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

