export { default as Building } from './building'
export { default as Troop } from './troop'
export { default as Village } from './village'
export * from './building'
export * from './troop'
export * from './village'