// @generated by protoc-gen-connect-query v0.4.0 with parameter "target=ts"
// @generated from file server/server.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import { GetEntityRequest, GetEntityResponse } from "./server_pb.js";

export const typeName = "Service";

/**
 * @generated from rpc Service.GetEntity
 */
export const getEntity = createQueryService({
  service: {
    methods: {
      getEntity: {
        name: "GetEntity",
        kind: MethodKind.Unary,
        I: GetEntityRequest,
        O: GetEntityResponse,
      },
    },
    typeName: "Service",
  },
}).getEntity;
