// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/v1/server.proto

package serverv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
	v1 "war-of-faith/pkg/protobuf/server/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "server.v1.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceGetVillageProcedure is the fully-qualified name of the Service's GetVillage RPC.
	ServiceGetVillageProcedure = "/server.v1.Service/GetVillage"
	// ServiceGetVillagesProcedure is the fully-qualified name of the Service's GetVillages RPC.
	ServiceGetVillagesProcedure = "/server.v1.Service/GetVillages"
	// ServiceGetBuildingsProcedure is the fully-qualified name of the Service's GetBuildings RPC.
	ServiceGetBuildingsProcedure = "/server.v1.Service/GetBuildings"
	// ServiceIssueBuildingUpgradeOrderProcedure is the fully-qualified name of the Service's
	// IssueBuildingUpgradeOrder RPC.
	ServiceIssueBuildingUpgradeOrderProcedure = "/server.v1.Service/IssueBuildingUpgradeOrder"
	// ServiceCancelBuildingUpgradeOrderProcedure is the fully-qualified name of the Service's
	// CancelBuildingUpgradeOrder RPC.
	ServiceCancelBuildingUpgradeOrderProcedure = "/server.v1.Service/CancelBuildingUpgradeOrder"
	// ServiceGetTroopsProcedure is the fully-qualified name of the Service's GetTroops RPC.
	ServiceGetTroopsProcedure = "/server.v1.Service/GetTroops"
	// ServiceIssueTroopTrainingOrderProcedure is the fully-qualified name of the Service's
	// IssueTroopTrainingOrder RPC.
	ServiceIssueTroopTrainingOrderProcedure = "/server.v1.Service/IssueTroopTrainingOrder"
	// ServiceCancelTroopTrainingOrderProcedure is the fully-qualified name of the Service's
	// CancelTroopTrainingOrder RPC.
	ServiceCancelTroopTrainingOrderProcedure = "/server.v1.Service/CancelTroopTrainingOrder"
	// ServiceGetWorldProcedure is the fully-qualified name of the Service's GetWorld RPC.
	ServiceGetWorldProcedure = "/server.v1.Service/GetWorld"
	// ServiceAttackProcedure is the fully-qualified name of the Service's Attack RPC.
	ServiceAttackProcedure = "/server.v1.Service/Attack"
	// ServiceGetPlayerProcedure is the fully-qualified name of the Service's GetPlayer RPC.
	ServiceGetPlayerProcedure = "/server.v1.Service/GetPlayer"
)

// ServiceClient is a client for the server.v1.Service service.
type ServiceClient interface {
	// VILLAGES
	GetVillage(context.Context, *connect_go.Request[v1.GetVillageRequest]) (*connect_go.Response[v1.GetVillageResponse], error)
	GetVillages(context.Context, *connect_go.Request[v1.GetVillagesRequest]) (*connect_go.Response[v1.GetVillagesResponse], error)
	// BUILDINGS
	GetBuildings(context.Context, *connect_go.Request[v1.GetBuildingsRequest]) (*connect_go.Response[v1.GetBuildingsResponse], error)
	IssueBuildingUpgradeOrder(context.Context, *connect_go.Request[v1.IssueBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.IssueBuildingUpgradeOrderResponse], error)
	CancelBuildingUpgradeOrder(context.Context, *connect_go.Request[v1.CancelBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.CancelBuildingUpgradeOrderResponse], error)
	// TROOPS
	GetTroops(context.Context, *connect_go.Request[v1.GetTroopsRequest]) (*connect_go.Response[v1.GetTroopsResponse], error)
	IssueTroopTrainingOrder(context.Context, *connect_go.Request[v1.IssueTroopTrainingOrderRequest]) (*connect_go.Response[v1.IssueTroopTrainingOrderResponse], error)
	CancelTroopTrainingOrder(context.Context, *connect_go.Request[v1.CancelTroopTrainingOrderRequest]) (*connect_go.Response[v1.CancelTroopTrainingOrderResponse], error)
	// WORLD
	GetWorld(context.Context, *connect_go.Request[v1.GetWorldRequest]) (*connect_go.Response[v1.GetWorldResponse], error)
	Attack(context.Context, *connect_go.Request[v1.AttackRequest]) (*connect_go.Response[v1.AttackResponse], error)
	// PLAYERS
	GetPlayer(context.Context, *connect_go.Request[v1.GetPlayerRequest]) (*connect_go.Response[v1.GetPlayerResponse], error)
}

// NewServiceClient constructs a client for the server.v1.Service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &serviceClient{
		getVillage: connect_go.NewClient[v1.GetVillageRequest, v1.GetVillageResponse](
			httpClient,
			baseURL+ServiceGetVillageProcedure,
			opts...,
		),
		getVillages: connect_go.NewClient[v1.GetVillagesRequest, v1.GetVillagesResponse](
			httpClient,
			baseURL+ServiceGetVillagesProcedure,
			opts...,
		),
		getBuildings: connect_go.NewClient[v1.GetBuildingsRequest, v1.GetBuildingsResponse](
			httpClient,
			baseURL+ServiceGetBuildingsProcedure,
			opts...,
		),
		issueBuildingUpgradeOrder: connect_go.NewClient[v1.IssueBuildingUpgradeOrderRequest, v1.IssueBuildingUpgradeOrderResponse](
			httpClient,
			baseURL+ServiceIssueBuildingUpgradeOrderProcedure,
			opts...,
		),
		cancelBuildingUpgradeOrder: connect_go.NewClient[v1.CancelBuildingUpgradeOrderRequest, v1.CancelBuildingUpgradeOrderResponse](
			httpClient,
			baseURL+ServiceCancelBuildingUpgradeOrderProcedure,
			opts...,
		),
		getTroops: connect_go.NewClient[v1.GetTroopsRequest, v1.GetTroopsResponse](
			httpClient,
			baseURL+ServiceGetTroopsProcedure,
			opts...,
		),
		issueTroopTrainingOrder: connect_go.NewClient[v1.IssueTroopTrainingOrderRequest, v1.IssueTroopTrainingOrderResponse](
			httpClient,
			baseURL+ServiceIssueTroopTrainingOrderProcedure,
			opts...,
		),
		cancelTroopTrainingOrder: connect_go.NewClient[v1.CancelTroopTrainingOrderRequest, v1.CancelTroopTrainingOrderResponse](
			httpClient,
			baseURL+ServiceCancelTroopTrainingOrderProcedure,
			opts...,
		),
		getWorld: connect_go.NewClient[v1.GetWorldRequest, v1.GetWorldResponse](
			httpClient,
			baseURL+ServiceGetWorldProcedure,
			opts...,
		),
		attack: connect_go.NewClient[v1.AttackRequest, v1.AttackResponse](
			httpClient,
			baseURL+ServiceAttackProcedure,
			opts...,
		),
		getPlayer: connect_go.NewClient[v1.GetPlayerRequest, v1.GetPlayerResponse](
			httpClient,
			baseURL+ServiceGetPlayerProcedure,
			opts...,
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	getVillage                 *connect_go.Client[v1.GetVillageRequest, v1.GetVillageResponse]
	getVillages                *connect_go.Client[v1.GetVillagesRequest, v1.GetVillagesResponse]
	getBuildings               *connect_go.Client[v1.GetBuildingsRequest, v1.GetBuildingsResponse]
	issueBuildingUpgradeOrder  *connect_go.Client[v1.IssueBuildingUpgradeOrderRequest, v1.IssueBuildingUpgradeOrderResponse]
	cancelBuildingUpgradeOrder *connect_go.Client[v1.CancelBuildingUpgradeOrderRequest, v1.CancelBuildingUpgradeOrderResponse]
	getTroops                  *connect_go.Client[v1.GetTroopsRequest, v1.GetTroopsResponse]
	issueTroopTrainingOrder    *connect_go.Client[v1.IssueTroopTrainingOrderRequest, v1.IssueTroopTrainingOrderResponse]
	cancelTroopTrainingOrder   *connect_go.Client[v1.CancelTroopTrainingOrderRequest, v1.CancelTroopTrainingOrderResponse]
	getWorld                   *connect_go.Client[v1.GetWorldRequest, v1.GetWorldResponse]
	attack                     *connect_go.Client[v1.AttackRequest, v1.AttackResponse]
	getPlayer                  *connect_go.Client[v1.GetPlayerRequest, v1.GetPlayerResponse]
}

// GetVillage calls server.v1.Service.GetVillage.
func (c *serviceClient) GetVillage(ctx context.Context, req *connect_go.Request[v1.GetVillageRequest]) (*connect_go.Response[v1.GetVillageResponse], error) {
	return c.getVillage.CallUnary(ctx, req)
}

// GetVillages calls server.v1.Service.GetVillages.
func (c *serviceClient) GetVillages(ctx context.Context, req *connect_go.Request[v1.GetVillagesRequest]) (*connect_go.Response[v1.GetVillagesResponse], error) {
	return c.getVillages.CallUnary(ctx, req)
}

// GetBuildings calls server.v1.Service.GetBuildings.
func (c *serviceClient) GetBuildings(ctx context.Context, req *connect_go.Request[v1.GetBuildingsRequest]) (*connect_go.Response[v1.GetBuildingsResponse], error) {
	return c.getBuildings.CallUnary(ctx, req)
}

// IssueBuildingUpgradeOrder calls server.v1.Service.IssueBuildingUpgradeOrder.
func (c *serviceClient) IssueBuildingUpgradeOrder(ctx context.Context, req *connect_go.Request[v1.IssueBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.IssueBuildingUpgradeOrderResponse], error) {
	return c.issueBuildingUpgradeOrder.CallUnary(ctx, req)
}

// CancelBuildingUpgradeOrder calls server.v1.Service.CancelBuildingUpgradeOrder.
func (c *serviceClient) CancelBuildingUpgradeOrder(ctx context.Context, req *connect_go.Request[v1.CancelBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.CancelBuildingUpgradeOrderResponse], error) {
	return c.cancelBuildingUpgradeOrder.CallUnary(ctx, req)
}

// GetTroops calls server.v1.Service.GetTroops.
func (c *serviceClient) GetTroops(ctx context.Context, req *connect_go.Request[v1.GetTroopsRequest]) (*connect_go.Response[v1.GetTroopsResponse], error) {
	return c.getTroops.CallUnary(ctx, req)
}

// IssueTroopTrainingOrder calls server.v1.Service.IssueTroopTrainingOrder.
func (c *serviceClient) IssueTroopTrainingOrder(ctx context.Context, req *connect_go.Request[v1.IssueTroopTrainingOrderRequest]) (*connect_go.Response[v1.IssueTroopTrainingOrderResponse], error) {
	return c.issueTroopTrainingOrder.CallUnary(ctx, req)
}

// CancelTroopTrainingOrder calls server.v1.Service.CancelTroopTrainingOrder.
func (c *serviceClient) CancelTroopTrainingOrder(ctx context.Context, req *connect_go.Request[v1.CancelTroopTrainingOrderRequest]) (*connect_go.Response[v1.CancelTroopTrainingOrderResponse], error) {
	return c.cancelTroopTrainingOrder.CallUnary(ctx, req)
}

// GetWorld calls server.v1.Service.GetWorld.
func (c *serviceClient) GetWorld(ctx context.Context, req *connect_go.Request[v1.GetWorldRequest]) (*connect_go.Response[v1.GetWorldResponse], error) {
	return c.getWorld.CallUnary(ctx, req)
}

// Attack calls server.v1.Service.Attack.
func (c *serviceClient) Attack(ctx context.Context, req *connect_go.Request[v1.AttackRequest]) (*connect_go.Response[v1.AttackResponse], error) {
	return c.attack.CallUnary(ctx, req)
}

// GetPlayer calls server.v1.Service.GetPlayer.
func (c *serviceClient) GetPlayer(ctx context.Context, req *connect_go.Request[v1.GetPlayerRequest]) (*connect_go.Response[v1.GetPlayerResponse], error) {
	return c.getPlayer.CallUnary(ctx, req)
}

// ServiceHandler is an implementation of the server.v1.Service service.
type ServiceHandler interface {
	// VILLAGES
	GetVillage(context.Context, *connect_go.Request[v1.GetVillageRequest]) (*connect_go.Response[v1.GetVillageResponse], error)
	GetVillages(context.Context, *connect_go.Request[v1.GetVillagesRequest]) (*connect_go.Response[v1.GetVillagesResponse], error)
	// BUILDINGS
	GetBuildings(context.Context, *connect_go.Request[v1.GetBuildingsRequest]) (*connect_go.Response[v1.GetBuildingsResponse], error)
	IssueBuildingUpgradeOrder(context.Context, *connect_go.Request[v1.IssueBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.IssueBuildingUpgradeOrderResponse], error)
	CancelBuildingUpgradeOrder(context.Context, *connect_go.Request[v1.CancelBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.CancelBuildingUpgradeOrderResponse], error)
	// TROOPS
	GetTroops(context.Context, *connect_go.Request[v1.GetTroopsRequest]) (*connect_go.Response[v1.GetTroopsResponse], error)
	IssueTroopTrainingOrder(context.Context, *connect_go.Request[v1.IssueTroopTrainingOrderRequest]) (*connect_go.Response[v1.IssueTroopTrainingOrderResponse], error)
	CancelTroopTrainingOrder(context.Context, *connect_go.Request[v1.CancelTroopTrainingOrderRequest]) (*connect_go.Response[v1.CancelTroopTrainingOrderResponse], error)
	// WORLD
	GetWorld(context.Context, *connect_go.Request[v1.GetWorldRequest]) (*connect_go.Response[v1.GetWorldResponse], error)
	Attack(context.Context, *connect_go.Request[v1.AttackRequest]) (*connect_go.Response[v1.AttackResponse], error)
	// PLAYERS
	GetPlayer(context.Context, *connect_go.Request[v1.GetPlayerRequest]) (*connect_go.Response[v1.GetPlayerResponse], error)
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	serviceGetVillageHandler := connect_go.NewUnaryHandler(
		ServiceGetVillageProcedure,
		svc.GetVillage,
		opts...,
	)
	serviceGetVillagesHandler := connect_go.NewUnaryHandler(
		ServiceGetVillagesProcedure,
		svc.GetVillages,
		opts...,
	)
	serviceGetBuildingsHandler := connect_go.NewUnaryHandler(
		ServiceGetBuildingsProcedure,
		svc.GetBuildings,
		opts...,
	)
	serviceIssueBuildingUpgradeOrderHandler := connect_go.NewUnaryHandler(
		ServiceIssueBuildingUpgradeOrderProcedure,
		svc.IssueBuildingUpgradeOrder,
		opts...,
	)
	serviceCancelBuildingUpgradeOrderHandler := connect_go.NewUnaryHandler(
		ServiceCancelBuildingUpgradeOrderProcedure,
		svc.CancelBuildingUpgradeOrder,
		opts...,
	)
	serviceGetTroopsHandler := connect_go.NewUnaryHandler(
		ServiceGetTroopsProcedure,
		svc.GetTroops,
		opts...,
	)
	serviceIssueTroopTrainingOrderHandler := connect_go.NewUnaryHandler(
		ServiceIssueTroopTrainingOrderProcedure,
		svc.IssueTroopTrainingOrder,
		opts...,
	)
	serviceCancelTroopTrainingOrderHandler := connect_go.NewUnaryHandler(
		ServiceCancelTroopTrainingOrderProcedure,
		svc.CancelTroopTrainingOrder,
		opts...,
	)
	serviceGetWorldHandler := connect_go.NewUnaryHandler(
		ServiceGetWorldProcedure,
		svc.GetWorld,
		opts...,
	)
	serviceAttackHandler := connect_go.NewUnaryHandler(
		ServiceAttackProcedure,
		svc.Attack,
		opts...,
	)
	serviceGetPlayerHandler := connect_go.NewUnaryHandler(
		ServiceGetPlayerProcedure,
		svc.GetPlayer,
		opts...,
	)
	return "/server.v1.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceGetVillageProcedure:
			serviceGetVillageHandler.ServeHTTP(w, r)
		case ServiceGetVillagesProcedure:
			serviceGetVillagesHandler.ServeHTTP(w, r)
		case ServiceGetBuildingsProcedure:
			serviceGetBuildingsHandler.ServeHTTP(w, r)
		case ServiceIssueBuildingUpgradeOrderProcedure:
			serviceIssueBuildingUpgradeOrderHandler.ServeHTTP(w, r)
		case ServiceCancelBuildingUpgradeOrderProcedure:
			serviceCancelBuildingUpgradeOrderHandler.ServeHTTP(w, r)
		case ServiceGetTroopsProcedure:
			serviceGetTroopsHandler.ServeHTTP(w, r)
		case ServiceIssueTroopTrainingOrderProcedure:
			serviceIssueTroopTrainingOrderHandler.ServeHTTP(w, r)
		case ServiceCancelTroopTrainingOrderProcedure:
			serviceCancelTroopTrainingOrderHandler.ServeHTTP(w, r)
		case ServiceGetWorldProcedure:
			serviceGetWorldHandler.ServeHTTP(w, r)
		case ServiceAttackProcedure:
			serviceAttackHandler.ServeHTTP(w, r)
		case ServiceGetPlayerProcedure:
			serviceGetPlayerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) GetVillage(context.Context, *connect_go.Request[v1.GetVillageRequest]) (*connect_go.Response[v1.GetVillageResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.GetVillage is not implemented"))
}

func (UnimplementedServiceHandler) GetVillages(context.Context, *connect_go.Request[v1.GetVillagesRequest]) (*connect_go.Response[v1.GetVillagesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.GetVillages is not implemented"))
}

func (UnimplementedServiceHandler) GetBuildings(context.Context, *connect_go.Request[v1.GetBuildingsRequest]) (*connect_go.Response[v1.GetBuildingsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.GetBuildings is not implemented"))
}

func (UnimplementedServiceHandler) IssueBuildingUpgradeOrder(context.Context, *connect_go.Request[v1.IssueBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.IssueBuildingUpgradeOrderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.IssueBuildingUpgradeOrder is not implemented"))
}

func (UnimplementedServiceHandler) CancelBuildingUpgradeOrder(context.Context, *connect_go.Request[v1.CancelBuildingUpgradeOrderRequest]) (*connect_go.Response[v1.CancelBuildingUpgradeOrderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.CancelBuildingUpgradeOrder is not implemented"))
}

func (UnimplementedServiceHandler) GetTroops(context.Context, *connect_go.Request[v1.GetTroopsRequest]) (*connect_go.Response[v1.GetTroopsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.GetTroops is not implemented"))
}

func (UnimplementedServiceHandler) IssueTroopTrainingOrder(context.Context, *connect_go.Request[v1.IssueTroopTrainingOrderRequest]) (*connect_go.Response[v1.IssueTroopTrainingOrderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.IssueTroopTrainingOrder is not implemented"))
}

func (UnimplementedServiceHandler) CancelTroopTrainingOrder(context.Context, *connect_go.Request[v1.CancelTroopTrainingOrderRequest]) (*connect_go.Response[v1.CancelTroopTrainingOrderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.CancelTroopTrainingOrder is not implemented"))
}

func (UnimplementedServiceHandler) GetWorld(context.Context, *connect_go.Request[v1.GetWorldRequest]) (*connect_go.Response[v1.GetWorldResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.GetWorld is not implemented"))
}

func (UnimplementedServiceHandler) Attack(context.Context, *connect_go.Request[v1.AttackRequest]) (*connect_go.Response[v1.AttackResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.Attack is not implemented"))
}

func (UnimplementedServiceHandler) GetPlayer(context.Context, *connect_go.Request[v1.GetPlayerRequest]) (*connect_go.Response[v1.GetPlayerResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.v1.Service.GetPlayer is not implemented"))
}
