// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file server/v1/server.proto (package server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelAttackRequest, CancelAttackResponse, CancelBuildingUpgradeOrderRequest, CancelBuildingUpgradeOrderResponse, CancelResourceTransferOrderRequest, CancelResourceTransferOrderResponse, CancelTroopTrainingOrderRequest, CancelTroopTrainingOrderResponse, GetWorldRequest, GetWorldResponse, IssueAttackRequest, IssueAttackResponse, IssueBuildingUpgradeOrderRequest, IssueBuildingUpgradeOrderResponse, IssueResourceTransferOrderRequest, IssueResourceTransferOrderResponse, IssueTroopTrainingOrderRequest, IssueTroopTrainingOrderResponse, SubscribeToWorldRequest, SubscribeToWorldResponse } from "./server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.v1.Service
 */
export const Service = {
  typeName: "server.v1.Service",
  methods: {
    /**
     * WORLD 
     *
     * @generated from rpc server.v1.Service.GetWorld
     */
    getWorld: {
      name: "GetWorld",
      I: GetWorldRequest,
      O: GetWorldResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.SubscribeToWorld
     */
    subscribeToWorld: {
      name: "SubscribeToWorld",
      I: SubscribeToWorldRequest,
      O: SubscribeToWorldResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc server.v1.Service.IssueAttack
     */
    issueAttack: {
      name: "IssueAttack",
      I: IssueAttackRequest,
      O: IssueAttackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.CancelAttack
     */
    cancelAttack: {
      name: "CancelAttack",
      I: CancelAttackRequest,
      O: CancelAttackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * VILLAGES 
     *
     * @generated from rpc server.v1.Service.IssueBuildingUpgradeOrder
     */
    issueBuildingUpgradeOrder: {
      name: "IssueBuildingUpgradeOrder",
      I: IssueBuildingUpgradeOrderRequest,
      O: IssueBuildingUpgradeOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.CancelBuildingUpgradeOrder
     */
    cancelBuildingUpgradeOrder: {
      name: "CancelBuildingUpgradeOrder",
      I: CancelBuildingUpgradeOrderRequest,
      O: CancelBuildingUpgradeOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.IssueTroopTrainingOrder
     */
    issueTroopTrainingOrder: {
      name: "IssueTroopTrainingOrder",
      I: IssueTroopTrainingOrderRequest,
      O: IssueTroopTrainingOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.CancelTroopTrainingOrder
     */
    cancelTroopTrainingOrder: {
      name: "CancelTroopTrainingOrder",
      I: CancelTroopTrainingOrderRequest,
      O: CancelTroopTrainingOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.IssueResourceTransferOrder
     */
    issueResourceTransferOrder: {
      name: "IssueResourceTransferOrder",
      I: IssueResourceTransferOrderRequest,
      O: IssueResourceTransferOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.CancelResourceTransferOrder
     */
    cancelResourceTransferOrder: {
      name: "CancelResourceTransferOrder",
      I: CancelResourceTransferOrderRequest,
      O: CancelResourceTransferOrderResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

