// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file server/v1/server.proto (package server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelTroopTrainingOrderRequest, CancelTroopTrainingOrderResponse, CancelUpgradeBuildingRequest, CancelUpgradeBuildingResponse, GetVillageRequest, GetVillageResponse, GetWorldRequest, GetWorldResponse, IssueTroopTrainingOrderRequest, IssueTroopTrainingOrderResponse, UpgradeBuildingRequest, UpgradeBuildingResponse } from "./server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.v1.Service
 */
export const Service = {
  typeName: "server.v1.Service",
  methods: {
    /**
     * VILLAGES 
     *
     * @generated from rpc server.v1.Service.GetVillage
     */
    getVillage: {
      name: "GetVillage",
      I: GetVillageRequest,
      O: GetVillageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ORDERS 
     *
     * @generated from rpc server.v1.Service.UpgradeBuilding
     */
    upgradeBuilding: {
      name: "UpgradeBuilding",
      I: UpgradeBuildingRequest,
      O: UpgradeBuildingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.CancelUpgradeBuilding
     */
    cancelUpgradeBuilding: {
      name: "CancelUpgradeBuilding",
      I: CancelUpgradeBuildingRequest,
      O: CancelUpgradeBuildingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.IssueTroopTrainingOrder
     */
    issueTroopTrainingOrder: {
      name: "IssueTroopTrainingOrder",
      I: IssueTroopTrainingOrderRequest,
      O: IssueTroopTrainingOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.v1.Service.CancelTroopTrainingOrder
     */
    cancelTroopTrainingOrder: {
      name: "CancelTroopTrainingOrder",
      I: CancelTroopTrainingOrderRequest,
      O: CancelTroopTrainingOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * WORLD 
     *
     * @generated from rpc server.v1.Service.GetWorld
     */
    getWorld: {
      name: "GetWorld",
      I: GetWorldRequest,
      O: GetWorldResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

