// @generated by protoc-gen-connect-query v0.4.0 with parameter "target=ts"
// @generated from file server/v1/server.proto (package server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import { GetVillageRequest, GetVillageResponse } from "./server_pb.js";

export const typeName = "server.v1.Service";

/**
 * @generated from rpc server.v1.Service.GetVillage
 */
export const getVillage = createQueryService({
  service: {
    methods: {
      getVillage: {
        name: "GetVillage",
        kind: MethodKind.Unary,
        I: GetVillageRequest,
        O: GetVillageResponse,
      },
    },
    typeName: "server.v1.Service",
  },
}).getVillage;
